### ISSUE TITLE
Total Recall for listtype v1

### ISSUE THREAD

**Issue by freshteapot** [freshteapot/learnalist-mobile#2]
I want to test myself on random items from ListType.v1.

# Aim
* pick 7
* display items at speed
* display recall page to see how many I recall.

# Todo
- [x] Share what I have already done.
- [x] What happens once I get the answers right?
- [x] Need info blurb.
